test:
  host: "127.0.0.1"
  port: 6379
  db: 3
  session_db: 5
development:
  host: "127.0.0.1"
  port: 6379
  db: 0
  session_db: 1
stage:
  host: "127.0.0.1"
  port: 6379
  db: 0
  session_db: 1
production:
  host: "127.0.0.1"
  port: 6379
  db: 0
  session_db: 1
