# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "sinatra-redis-auth"
  s.version = "0.1.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Ondrej Bartas"]
  s.date = "2012-03-08"
  s.description = "Sinatra authentification with saving user data to redis"
  s.email = "ondrej@bartas.cz"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "config/mail_config.rb.example",
    "config/redis_config.yml.example",
    "example/config.ru",
    "example/config/mail_config.rb",
    "example/config/redis_config.yml",
    "example/example_app.rb",
    "example/user.rb",
    "example/views/index.erb",
    "example/views/layout.erb",
    "example/views/protected_page.erb",
    "lib/mailer.rb",
    "lib/session_database.rb",
    "lib/sinatra-redis-auth.rb",
    "lib/user_auth_model.rb",
    "lib/views/password_change.erb",
    "lib/views/password_reset.erb",
    "lib/views/sign_in.erb",
    "lib/views/sign_up.erb",
    "sinatra-redis-auth.gemspec",
    "test/helper.rb",
    "test/test_sinatra-redis-auth.rb"
  ]
  s.homepage = "http://github.com/ondrejbartas/sinatra-redis-auth"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.10"
  s.summary = "Sinatra authentification with saving user data to redis"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rainbows>, [">= 0"])
      s.add_runtime_dependency(%q<sinatra>, ["~> 1.2.6"])
      s.add_runtime_dependency(%q<redis-model-extension>, ["~> 0.2.0"])
      s.add_runtime_dependency(%q<rake>, [">= 0"])
      s.add_runtime_dependency(%q<rack>, ["~> 1.3.0"])
      s.add_runtime_dependency(%q<rack-flash>, [">= 0"])
      s.add_runtime_dependency(%q<tilt>, ["~> 1.3.2"])
      s.add_runtime_dependency(%q<redis-rack>, [">= 0"])
      s.add_runtime_dependency(%q<mail>, [">= 0"])
      s.add_development_dependency(%q<shoulda>, [">= 0"])
      s.add_development_dependency(%q<shoulda-context>, [">= 0"])
      s.add_development_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.8.3"])
      s.add_development_dependency(%q<turn>, ["~> 0.8.2"])
      s.add_development_dependency(%q<minitest>, [">= 0"])
      s.add_development_dependency(%q<ansi>, ["~> 1.2.5"])
      s.add_development_dependency(%q<thin>, [">= 0"])
      s.add_development_dependency(%q<shotgun>, [">= 0"])
    else
      s.add_dependency(%q<rainbows>, [">= 0"])
      s.add_dependency(%q<sinatra>, ["~> 1.2.6"])
      s.add_dependency(%q<redis-model-extension>, ["~> 0.2.0"])
      s.add_dependency(%q<rake>, [">= 0"])
      s.add_dependency(%q<rack>, ["~> 1.3.0"])
      s.add_dependency(%q<rack-flash>, [">= 0"])
      s.add_dependency(%q<tilt>, ["~> 1.3.2"])
      s.add_dependency(%q<redis-rack>, [">= 0"])
      s.add_dependency(%q<mail>, [">= 0"])
      s.add_dependency(%q<shoulda>, [">= 0"])
      s.add_dependency(%q<shoulda-context>, [">= 0"])
      s.add_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.8.3"])
      s.add_dependency(%q<turn>, ["~> 0.8.2"])
      s.add_dependency(%q<minitest>, [">= 0"])
      s.add_dependency(%q<ansi>, ["~> 1.2.5"])
      s.add_dependency(%q<thin>, [">= 0"])
      s.add_dependency(%q<shotgun>, [">= 0"])
    end
  else
    s.add_dependency(%q<rainbows>, [">= 0"])
    s.add_dependency(%q<sinatra>, ["~> 1.2.6"])
    s.add_dependency(%q<redis-model-extension>, ["~> 0.2.0"])
    s.add_dependency(%q<rake>, [">= 0"])
    s.add_dependency(%q<rack>, ["~> 1.3.0"])
    s.add_dependency(%q<rack-flash>, [">= 0"])
    s.add_dependency(%q<tilt>, ["~> 1.3.2"])
    s.add_dependency(%q<redis-rack>, [">= 0"])
    s.add_dependency(%q<mail>, [">= 0"])
    s.add_dependency(%q<shoulda>, [">= 0"])
    s.add_dependency(%q<shoulda-context>, [">= 0"])
    s.add_dependency(%q<rdoc>, ["~> 3.12"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.8.3"])
    s.add_dependency(%q<turn>, ["~> 0.8.2"])
    s.add_dependency(%q<minitest>, [">= 0"])
    s.add_dependency(%q<ansi>, ["~> 1.2.5"])
    s.add_dependency(%q<thin>, [">= 0"])
    s.add_dependency(%q<shotgun>, [">= 0"])
  end
end

